regression:
  contract_version: v3
  destination:
    samples_directory: samples
  combinations:
    - application_type: backend
      protocol: rest
      language: javascript
      framework: express
      data_fetch: in-memory
    - application_type: backend
      protocol: rest
      language: java
      framework: spring-boot
      data_fetch: in-memory
    - application_type: backend
      protocol: rest
      language: python
      framework: flask
      data_fetch: in-memory
    - application_type: backend
      protocol: rest
      language: typescript
      framework: express
      data_fetch: in-memory
    - application_type: bff
      protocol: rest
      language: javascript
      framework: express
      data_fetch: rest-api
    - application_type: bff
      protocol: rest
      language: java
      framework: spring-boot
      data_fetch: rest-api
    - application_type: frontend
      protocol: rest
      language: javascript
      framework: express
      data_fetch: rest-api
