application_types:
  - backend
  - bff
  - frontend

protocols:
  - rest

languages:
  - javascript
  - typescript
  - java
  - python

frameworks:
  - express
  - spring-boot
  - flask

data_fetch_modes:
  - in-memory
  - rest-api
